// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TeacherPortfolio.API.Models;

#nullable disable

namespace TeacherPortfolio.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TeacherPortfolio.API.Models.AcademicPerformance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("integer")
                        .HasColumnName("academicyearid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Discipline")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("discipline");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("groupname");

                    b.Property<decimal>("QualityPercent")
                        .HasColumnType("numeric")
                        .HasColumnName("quality_percent");

                    b.Property<decimal>("SuccessPercent")
                        .HasColumnType("numeric")
                        .HasColumnName("success_percent");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacherid");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("TeacherId");

                    b.ToTable("academic_performances");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Academicresult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Academicyearid")
                        .HasColumnType("integer")
                        .HasColumnName("academicyearid");

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Groupid")
                        .HasColumnType("integer")
                        .HasColumnName("groupid");

                    b.Property<decimal>("Qualitypercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("qualitypercent");

                    b.Property<int>("Subjectid")
                        .HasColumnType("integer")
                        .HasColumnName("subjectid");

                    b.Property<decimal>("Successpercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("successpercent");

                    b.Property<int>("Teacherid")
                        .HasColumnType("integer")
                        .HasColumnName("teacherid");

                    b.HasKey("Id")
                        .HasName("academicresults_pkey");

                    b.HasIndex("Academicyearid");

                    b.HasIndex("Groupid");

                    b.HasIndex("Subjectid");

                    b.HasIndex("Teacherid");

                    b.ToTable("academicresults");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Academicyear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("academicyears_pkey");

                    b.HasIndex(new[] { "Name" }, "academicyears_name_key")
                        .IsUnique();

                    b.ToTable("academicyears");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Contest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Academicyearid")
                        .HasColumnType("integer")
                        .HasColumnName("academicyearid");

                    b.Property<string>("Contestname")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("contestname");

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Levelid")
                        .HasColumnType("integer")
                        .HasColumnName("levelid");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("link");

                    b.Property<string>("Orderdetails")
                        .HasColumnType("text")
                        .HasColumnName("orderdetails");

                    b.Property<string>("Organizer")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("organizer");

                    b.Property<string>("Resultdescription")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("resultdescription");

                    b.Property<int?>("Resultid")
                        .HasColumnType("integer")
                        .HasColumnName("resultid");

                    b.Property<int>("Teacherid")
                        .HasColumnType("integer")
                        .HasColumnName("teacherid");

                    b.HasKey("Id")
                        .HasName("contests_pkey");

                    b.HasIndex("Academicyearid");

                    b.HasIndex("Levelid");

                    b.HasIndex("Resultid");

                    b.HasIndex("Teacherid");

                    b.ToTable("contests");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Departmentactivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Academicyearid")
                        .HasColumnType("integer")
                        .HasColumnName("academicyearid");

                    b.Property<int>("Activitytypeid")
                        .HasColumnType("integer")
                        .HasColumnName("activitytypeid");

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Documentlink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("documentlink");

                    b.Property<string>("Orderdetails")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("orderdetails");

                    b.Property<int>("Teacherid")
                        .HasColumnType("integer")
                        .HasColumnName("teacherid");

                    b.HasKey("Id")
                        .HasName("departmentactivities_pkey");

                    b.HasIndex("Academicyearid");

                    b.HasIndex("Activitytypeid");

                    b.HasIndex("Teacherid");

                    b.ToTable("departmentactivities");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Departmentactivitytype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("departmentactivitytypes_pkey");

                    b.ToTable("departmentactivitytypes");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Digitalresource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Academicyearid")
                        .HasColumnType("integer")
                        .HasColumnName("academicyearid");

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Interactionform")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("interactionform");

                    b.Property<string>("Lessontopic")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("lessontopic");

                    b.Property<string>("Resourcelink")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("resourcelink");

                    b.Property<string>("Resourcename")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("resourcename");

                    b.Property<int>("Teacherid")
                        .HasColumnType("integer")
                        .HasColumnName("teacherid");

                    b.HasKey("Id")
                        .HasName("digitalresources_pkey");

                    b.HasIndex("Academicyearid");

                    b.HasIndex("Teacherid");

                    b.ToTable("digitalresources");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Educationaltechnology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Purpose")
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<string>("Resourcelink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("resourcelink");

                    b.Property<string>("Result")
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<int>("Teacherid")
                        .HasColumnType("integer")
                        .HasColumnName("teacherid");

                    b.Property<string>("Technologyname")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("technologyname");

                    b.HasKey("Id")
                        .HasName("educationaltechnologies_pkey");

                    b.HasIndex("Teacherid");

                    b.ToTable("educationaltechnologies");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.ElectronicResource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("integer")
                        .HasColumnName("academicyearid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("InteractionForm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("interaction_form");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("link");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacherid");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("topic");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("TeacherId");

                    b.ToTable("electronic_resources");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Eventdirection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("eventdirections_pkey");

                    b.ToTable("eventdirections");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Eventformat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("eventformats_pkey");

                    b.ToTable("eventformats");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Eventlevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("eventlevels_pkey");

                    b.ToTable("eventlevels");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Experiencesharing", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateOnly>("Eventdate")
                        .HasColumnType("date")
                        .HasColumnName("eventdate");

                    b.Property<string>("Eventname")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("eventname");

                    b.Property<int?>("Formatid")
                        .HasColumnType("integer")
                        .HasColumnName("formatid");

                    b.Property<int>("Levelid")
                        .HasColumnType("integer")
                        .HasColumnName("levelid");

                    b.Property<string>("Organizer")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("organizer");

                    b.Property<int?>("Sharingformid")
                        .HasColumnType("integer")
                        .HasColumnName("sharingformid");

                    b.Property<int>("Teacherid")
                        .HasColumnType("integer")
                        .HasColumnName("teacherid");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("experiencesharing_pkey");

                    b.HasIndex("Formatid");

                    b.HasIndex("Levelid");

                    b.HasIndex("Sharingformid");

                    b.HasIndex("Teacherid");

                    b.ToTable("experiencesharing");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Experiencesharingform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("experiencesharingforms_pkey");

                    b.ToTable("experiencesharingforms");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Expertactivity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Academicyearid")
                        .HasColumnType("integer")
                        .HasColumnName("academicyearid");

                    b.Property<string>("Activitytype")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("activitytype");

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Documentdetails")
                        .HasColumnType("text")
                        .HasColumnName("documentdetails");

                    b.Property<DateOnly?>("Eventdate")
                        .HasColumnType("date")
                        .HasColumnName("eventdate");

                    b.Property<string>("Eventname")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("eventname");

                    b.Property<int>("Levelid")
                        .HasColumnType("integer")
                        .HasColumnName("levelid");

                    b.Property<int>("Teacherid")
                        .HasColumnType("integer")
                        .HasColumnName("teacherid");

                    b.HasKey("Id")
                        .HasName("expertactivities_pkey");

                    b.HasIndex("Academicyearid");

                    b.HasIndex("Levelid");

                    b.HasIndex("Teacherid");

                    b.ToTable("expertactivities");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Gradetype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("gradetypes_pkey");

                    b.ToTable("gradetypes");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Graduatework", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Academicyearid")
                        .HasColumnType("integer")
                        .HasColumnName("academicyearid");

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Gradeid")
                        .HasColumnType("integer")
                        .HasColumnName("gradeid");

                    b.Property<string>("Groupname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("groupname");

                    b.Property<string>("Specialty")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("specialty");

                    b.Property<string>("Studentname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("studentname");

                    b.Property<int>("Teacherid")
                        .HasColumnType("integer")
                        .HasColumnName("teacherid");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("graduateworks_pkey");

                    b.HasIndex("Academicyearid");

                    b.HasIndex("Gradeid");

                    b.HasIndex("Teacherid");

                    b.ToTable("graduateworks");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.GraduationResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("integer")
                        .HasColumnName("academicyearid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("grade");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("groupname");

                    b.Property<string>("Specialty")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("specialty");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("studentname");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacherid");

                    b.Property<string>("ThesisTopic")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("thesis_topic");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("TeacherId");

                    b.ToTable("graduation_results");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Methodicalmaterial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Academicyearid")
                        .HasColumnType("integer")
                        .HasColumnName("academicyearid");

                    b.Property<string>("Approvaldetails")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("approvaldetails");

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Internetlink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("internetlink");

                    b.Property<int>("Materialtypeid")
                        .HasColumnType("integer")
                        .HasColumnName("materialtypeid");

                    b.Property<string>("Reviewingorganization")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("reviewingorganization");

                    b.Property<string>("Specialty")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("specialty");

                    b.Property<int>("Teacherid")
                        .HasColumnType("integer")
                        .HasColumnName("teacherid");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("topic");

                    b.HasKey("Id")
                        .HasName("methodicalmaterials_pkey");

                    b.HasIndex("Academicyearid");

                    b.HasIndex("Materialtypeid");

                    b.HasIndex("Teacherid");

                    b.ToTable("methodicalmaterials");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Methodicalmaterialtype", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("methodicalmaterialtypes_pkey");

                    b.ToTable("methodicalmaterialtypes");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Participationresult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("participationresults_pkey");

                    b.ToTable("participationresults");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Qualificationcategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("qualificationcategories_pkey");

                    b.ToTable("qualificationcategories");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Studentachievement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Academicyearid")
                        .HasColumnType("integer")
                        .HasColumnName("academicyearid");

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("Directionid")
                        .HasColumnType("integer")
                        .HasColumnName("directionid");

                    b.Property<string>("Documentlink")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("documentlink");

                    b.Property<DateOnly>("Eventdate")
                        .HasColumnType("date")
                        .HasColumnName("eventdate");

                    b.Property<string>("Eventname")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("eventname");

                    b.Property<string>("Eventorganizer")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("eventorganizer");

                    b.Property<string>("Groupname")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("groupname");

                    b.Property<int>("Levelid")
                        .HasColumnType("integer")
                        .HasColumnName("levelid");

                    b.Property<string>("Orderdetails")
                        .HasColumnType("text")
                        .HasColumnName("orderdetails");

                    b.Property<string>("Resultdescription")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("resultdescription");

                    b.Property<int?>("Resultid")
                        .HasColumnType("integer")
                        .HasColumnName("resultid");

                    b.Property<string>("Studentname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("studentname");

                    b.Property<int>("Teacherid")
                        .HasColumnType("integer")
                        .HasColumnName("teacherid");

                    b.HasKey("Id")
                        .HasName("studentachievements_pkey");

                    b.HasIndex("Academicyearid");

                    b.HasIndex("Directionid");

                    b.HasIndex("Levelid");

                    b.HasIndex("Resultid");

                    b.HasIndex("Teacherid");

                    b.ToTable("studentachievements");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Studentgroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("Teacherid")
                        .HasColumnType("integer")
                        .HasColumnName("teacherid");

                    b.HasKey("Id")
                        .HasName("studentgroups_pkey");

                    b.HasIndex("Teacherid");

                    b.ToTable("studentgroups");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<string>("Shortname")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("shortname");

                    b.Property<int>("Teacherid")
                        .HasColumnType("integer")
                        .HasColumnName("teacherid");

                    b.HasKey("Id")
                        .HasName("subjects_pkey");

                    b.HasIndex("Teacherid");

                    b.ToTable("subjects");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("firstname");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("lastname");

                    b.Property<string>("Middlename")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("middlename");

                    b.Property<DateOnly?>("Orderdate")
                        .HasColumnType("date")
                        .HasColumnName("orderdate");

                    b.Property<string>("Ordernumber")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ordernumber");

                    b.Property<string>("Position")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("position");

                    b.Property<int?>("Qualificationcategoryid")
                        .HasColumnType("integer")
                        .HasColumnName("qualificationcategoryid");

                    b.Property<int>("Userid")
                        .HasColumnType("integer")
                        .HasColumnName("userid");

                    b.Property<string>("Workplace")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("workplace");

                    b.HasKey("Id")
                        .HasName("teachers_pkey");

                    b.HasIndex("Qualificationcategoryid");

                    b.HasIndex(new[] { "Userid" }, "teachers_userid_key")
                        .IsUnique();

                    b.ToTable("teachers");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.TeacherContest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("integer")
                        .HasColumnName("academicyearid");

                    b.Property<string>("ContestName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("contest_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("level");

                    b.Property<string>("Link")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("link");

                    b.Property<string>("OrderDetails")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("order_details");

                    b.Property<string>("Organizer")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("organizer");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("result");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer")
                        .HasColumnName("teacherid");

                    b.HasKey("Id");

                    b.HasIndex("AcademicYearId");

                    b.HasIndex("TeacherId");

                    b.ToTable("teacher_contests");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Createdat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Passwordhash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("passwordhash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.HasIndex(new[] { "Email" }, "users_email_key")
                        .IsUnique();

                    b.ToTable("users");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.AcademicPerformance", b =>
                {
                    b.HasOne("TeacherPortfolio.API.Models.Academicyear", "AcademicYear")
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeacherPortfolio.API.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Academicresult", b =>
                {
                    b.HasOne("TeacherPortfolio.API.Models.Academicyear", "Academicyear")
                        .WithMany("Academicresults")
                        .HasForeignKey("Academicyearid")
                        .IsRequired()
                        .HasConstraintName("academicresults_academicyearid_fkey");

                    b.HasOne("TeacherPortfolio.API.Models.Studentgroup", "Group")
                        .WithMany("Academicresults")
                        .HasForeignKey("Groupid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("academicresults_groupid_fkey");

                    b.HasOne("TeacherPortfolio.API.Models.Subject", "Subject")
                        .WithMany("Academicresults")
                        .HasForeignKey("Subjectid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("academicresults_subjectid_fkey");

                    b.HasOne("TeacherPortfolio.API.Models.Teacher", "Teacher")
                        .WithMany("Academicresults")
                        .HasForeignKey("Teacherid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("academicresults_teacherid_fkey");

                    b.Navigation("Academicyear");

                    b.Navigation("Group");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Contest", b =>
                {
                    b.HasOne("TeacherPortfolio.API.Models.Academicyear", "Academicyear")
                        .WithMany("Contests")
                        .HasForeignKey("Academicyearid")
                        .IsRequired()
                        .HasConstraintName("contests_academicyearid_fkey");

                    b.HasOne("TeacherPortfolio.API.Models.Eventlevel", "Level")
                        .WithMany("Contests")
                        .HasForeignKey("Levelid")
                        .IsRequired()
                        .HasConstraintName("contests_levelid_fkey");

                    b.HasOne("TeacherPortfolio.API.Models.Participationresult", "Result")
                        .WithMany("Contests")
                        .HasForeignKey("Resultid")
                        .HasConstraintName("contests_resultid_fkey");

                    b.HasOne("TeacherPortfolio.API.Models.Teacher", "Teacher")
                        .WithMany("Contests")
                        .HasForeignKey("Teacherid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("contests_teacherid_fkey");

                    b.Navigation("Academicyear");

                    b.Navigation("Level");

                    b.Navigation("Result");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Departmentactivity", b =>
                {
                    b.HasOne("TeacherPortfolio.API.Models.Academicyear", "Academicyear")
                        .WithMany("Departmentactivities")
                        .HasForeignKey("Academicyearid")
                        .IsRequired()
                        .HasConstraintName("departmentactivities_academicyearid_fkey");

                    b.HasOne("TeacherPortfolio.API.Models.Departmentactivitytype", "Activitytype")
                        .WithMany("Departmentactivities")
                        .HasForeignKey("Activitytypeid")
                        .IsRequired()
                        .HasConstraintName("departmentactivities_activitytypeid_fkey");

                    b.HasOne("TeacherPortfolio.API.Models.Teacher", "Teacher")
                        .WithMany("Departmentactivities")
                        .HasForeignKey("Teacherid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("departmentactivities_teacherid_fkey");

                    b.Navigation("Academicyear");

                    b.Navigation("Activitytype");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Digitalresource", b =>
                {
                    b.HasOne("TeacherPortfolio.API.Models.Academicyear", "Academicyear")
                        .WithMany("Digitalresources")
                        .HasForeignKey("Academicyearid")
                        .HasConstraintName("digitalresources_academicyearid_fkey");

                    b.HasOne("TeacherPortfolio.API.Models.Teacher", "Teacher")
                        .WithMany("Digitalresources")
                        .HasForeignKey("Teacherid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("digitalresources_teacherid_fkey");

                    b.Navigation("Academicyear");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Educationaltechnology", b =>
                {
                    b.HasOne("TeacherPortfolio.API.Models.Teacher", "Teacher")
                        .WithMany("Educationaltechnologies")
                        .HasForeignKey("Teacherid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("educationaltechnologies_teacherid_fkey");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.ElectronicResource", b =>
                {
                    b.HasOne("TeacherPortfolio.API.Models.Academicyear", "AcademicYear")
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeacherPortfolio.API.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Experiencesharing", b =>
                {
                    b.HasOne("TeacherPortfolio.API.Models.Eventformat", "Format")
                        .WithMany("Experiencesharings")
                        .HasForeignKey("Formatid")
                        .HasConstraintName("experiencesharing_formatid_fkey");

                    b.HasOne("TeacherPortfolio.API.Models.Eventlevel", "Level")
                        .WithMany("Experiencesharings")
                        .HasForeignKey("Levelid")
                        .IsRequired()
                        .HasConstraintName("experiencesharing_levelid_fkey");

                    b.HasOne("TeacherPortfolio.API.Models.Experiencesharingform", "Sharingform")
                        .WithMany("Experiencesharings")
                        .HasForeignKey("Sharingformid")
                        .HasConstraintName("experiencesharing_sharingformid_fkey");

                    b.HasOne("TeacherPortfolio.API.Models.Teacher", "Teacher")
                        .WithMany("Experiencesharings")
                        .HasForeignKey("Teacherid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("experiencesharing_teacherid_fkey");

                    b.Navigation("Format");

                    b.Navigation("Level");

                    b.Navigation("Sharingform");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Expertactivity", b =>
                {
                    b.HasOne("TeacherPortfolio.API.Models.Academicyear", "Academicyear")
                        .WithMany("Expertactivities")
                        .HasForeignKey("Academicyearid")
                        .HasConstraintName("expertactivities_academicyearid_fkey");

                    b.HasOne("TeacherPortfolio.API.Models.Eventlevel", "Level")
                        .WithMany("Expertactivities")
                        .HasForeignKey("Levelid")
                        .IsRequired()
                        .HasConstraintName("expertactivities_levelid_fkey");

                    b.HasOne("TeacherPortfolio.API.Models.Teacher", "Teacher")
                        .WithMany("Expertactivities")
                        .HasForeignKey("Teacherid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("expertactivities_teacherid_fkey");

                    b.Navigation("Academicyear");

                    b.Navigation("Level");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Graduatework", b =>
                {
                    b.HasOne("TeacherPortfolio.API.Models.Academicyear", "Academicyear")
                        .WithMany("Graduateworks")
                        .HasForeignKey("Academicyearid")
                        .IsRequired()
                        .HasConstraintName("graduateworks_academicyearid_fkey");

                    b.HasOne("TeacherPortfolio.API.Models.Gradetype", "Grade")
                        .WithMany("Graduateworks")
                        .HasForeignKey("Gradeid")
                        .IsRequired()
                        .HasConstraintName("graduateworks_gradeid_fkey");

                    b.HasOne("TeacherPortfolio.API.Models.Teacher", "Teacher")
                        .WithMany("Graduateworks")
                        .HasForeignKey("Teacherid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("graduateworks_teacherid_fkey");

                    b.Navigation("Academicyear");

                    b.Navigation("Grade");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.GraduationResult", b =>
                {
                    b.HasOne("TeacherPortfolio.API.Models.Academicyear", "AcademicYear")
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeacherPortfolio.API.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Methodicalmaterial", b =>
                {
                    b.HasOne("TeacherPortfolio.API.Models.Academicyear", "Academicyear")
                        .WithMany("Methodicalmaterials")
                        .HasForeignKey("Academicyearid")
                        .IsRequired()
                        .HasConstraintName("methodicalmaterials_academicyearid_fkey");

                    b.HasOne("TeacherPortfolio.API.Models.Methodicalmaterialtype", "Materialtype")
                        .WithMany("Methodicalmaterials")
                        .HasForeignKey("Materialtypeid")
                        .IsRequired()
                        .HasConstraintName("methodicalmaterials_materialtypeid_fkey");

                    b.HasOne("TeacherPortfolio.API.Models.Teacher", "Teacher")
                        .WithMany("Methodicalmaterials")
                        .HasForeignKey("Teacherid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("methodicalmaterials_teacherid_fkey");

                    b.Navigation("Academicyear");

                    b.Navigation("Materialtype");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Studentachievement", b =>
                {
                    b.HasOne("TeacherPortfolio.API.Models.Academicyear", "Academicyear")
                        .WithMany("Studentachievements")
                        .HasForeignKey("Academicyearid")
                        .IsRequired()
                        .HasConstraintName("studentachievements_academicyearid_fkey");

                    b.HasOne("TeacherPortfolio.API.Models.Eventdirection", "Direction")
                        .WithMany("Studentachievements")
                        .HasForeignKey("Directionid")
                        .HasConstraintName("studentachievements_directionid_fkey");

                    b.HasOne("TeacherPortfolio.API.Models.Eventlevel", "Level")
                        .WithMany("Studentachievements")
                        .HasForeignKey("Levelid")
                        .IsRequired()
                        .HasConstraintName("studentachievements_levelid_fkey");

                    b.HasOne("TeacherPortfolio.API.Models.Participationresult", "Result")
                        .WithMany("Studentachievements")
                        .HasForeignKey("Resultid")
                        .HasConstraintName("studentachievements_resultid_fkey");

                    b.HasOne("TeacherPortfolio.API.Models.Teacher", "Teacher")
                        .WithMany("Studentachievements")
                        .HasForeignKey("Teacherid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("studentachievements_teacherid_fkey");

                    b.Navigation("Academicyear");

                    b.Navigation("Direction");

                    b.Navigation("Level");

                    b.Navigation("Result");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Studentgroup", b =>
                {
                    b.HasOne("TeacherPortfolio.API.Models.Teacher", "Teacher")
                        .WithMany("Studentgroups")
                        .HasForeignKey("Teacherid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("studentgroups_teacherid_fkey");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Subject", b =>
                {
                    b.HasOne("TeacherPortfolio.API.Models.Teacher", "Teacher")
                        .WithMany("Subjects")
                        .HasForeignKey("Teacherid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("subjects_teacherid_fkey");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Teacher", b =>
                {
                    b.HasOne("TeacherPortfolio.API.Models.Qualificationcategory", "Qualificationcategory")
                        .WithMany("Teachers")
                        .HasForeignKey("Qualificationcategoryid")
                        .HasConstraintName("teachers_qualificationcategoryid_fkey");

                    b.HasOne("TeacherPortfolio.API.Models.User", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("TeacherPortfolio.API.Models.Teacher", "Userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("teachers_userid_fkey");

                    b.Navigation("Qualificationcategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.TeacherContest", b =>
                {
                    b.HasOne("TeacherPortfolio.API.Models.Academicyear", "AcademicYear")
                        .WithMany()
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeacherPortfolio.API.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcademicYear");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Academicyear", b =>
                {
                    b.Navigation("Academicresults");

                    b.Navigation("Contests");

                    b.Navigation("Departmentactivities");

                    b.Navigation("Digitalresources");

                    b.Navigation("Expertactivities");

                    b.Navigation("Graduateworks");

                    b.Navigation("Methodicalmaterials");

                    b.Navigation("Studentachievements");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Departmentactivitytype", b =>
                {
                    b.Navigation("Departmentactivities");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Eventdirection", b =>
                {
                    b.Navigation("Studentachievements");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Eventformat", b =>
                {
                    b.Navigation("Experiencesharings");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Eventlevel", b =>
                {
                    b.Navigation("Contests");

                    b.Navigation("Experiencesharings");

                    b.Navigation("Expertactivities");

                    b.Navigation("Studentachievements");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Experiencesharingform", b =>
                {
                    b.Navigation("Experiencesharings");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Gradetype", b =>
                {
                    b.Navigation("Graduateworks");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Methodicalmaterialtype", b =>
                {
                    b.Navigation("Methodicalmaterials");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Participationresult", b =>
                {
                    b.Navigation("Contests");

                    b.Navigation("Studentachievements");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Qualificationcategory", b =>
                {
                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Studentgroup", b =>
                {
                    b.Navigation("Academicresults");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Subject", b =>
                {
                    b.Navigation("Academicresults");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.Teacher", b =>
                {
                    b.Navigation("Academicresults");

                    b.Navigation("Contests");

                    b.Navigation("Departmentactivities");

                    b.Navigation("Digitalresources");

                    b.Navigation("Educationaltechnologies");

                    b.Navigation("Experiencesharings");

                    b.Navigation("Expertactivities");

                    b.Navigation("Graduateworks");

                    b.Navigation("Methodicalmaterials");

                    b.Navigation("Studentachievements");

                    b.Navigation("Studentgroups");

                    b.Navigation("Subjects");
                });

            modelBuilder.Entity("TeacherPortfolio.API.Models.User", b =>
                {
                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
